config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  root :to => 'freelancers/jobs#index', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Freelancer' }, :as => "freelancer_root"
  root :to => 'clients/jobs#index', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Client' }, :as => "client_root"

  # root 'freelancers/jobs#index'

  devise_for :freelancers, :controllers => { :registrations => :registrations }
  devise_for :clients, :controllers => { :registrations => :registrations }

  namespace :clients do
    resources :contracts
    resources :proposals
    resources :jobs
  end

  namespace :freelancers do
    resources :contracts
    resources :proposals
    resources :jobs

  end

   resources :freelancers
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jobs, dependent: :destroy
  has_many :proposals, through: :jobs
  has_many :contracts, through: :proposals

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :client

  scope :search_bar, -> (search) { where("title iLIKE ? OR description iLIKE ?", "%#{search}%", "%#{search}%") }
  # match pattern,                    wild_cards to match the search
  scope :filter_skills, -> (skills) { joins(:skills).where(skills: {name: skills}) }

  scope :recent, -> { order(created_at: :desc).limit(4) }

  with_options dependent: :destroy do
    has_many :proposals
    has_many :freelancers, through: :proposals
    has_and_belongs_to_many :skills
    # has_one :contract, through: :proposals
  end

  def applied? (current_freelancer)
    proposals.where(freelancer_id: current_freelancer.id).exists?
  end
end

app/controllers/clients/contracts_controller.rb
module Clients
  class ContractsController < ApplicationController

    before_action :authenticate_client!

    def index
      @contracts = current_client.contracts
    end


    def create
      @proposal = Proposal.find(params[:proposal_id])
      @contract = Contract.new
      @contract.start_date = DateTime.now
      @contract.start_date = @proposal.job.end_date
      @contract.proposal_id =  @proposal.id
      @contract.freelancer_id =  @proposal.freelancer_id
      @contract.save
      # redirect_back(fallback_location: clients_proposals_path(:job_id))
    end

    def update
      @contract = Contract.find(params[:id])
      @contract.update(end_date: DateTime.now)
      # redirect_back(fallback_location: root_path)
    end

  end
end

app/controllers/clients/jobs_controller.rb
module Clients
  class JobsController < ApplicationController
    before_action :authenticate_client!
    before_action :find_job, only: [:show, :edit, :destroy, :update]

    def index
      @jobs = current_client.jobs
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new(job_params.merge(client_id: current_client.id))
      # @job = Job.new(job_params)
      # @job.client_id = current_client.id
      if @job.save
        redirect_to clients_jobs_path, notice: 'job Created Successfully'
      else
        render :new
      end
    end

    def update
      if @job.update(job_params)
        redirect_to clients_job_path(@job), notice: 'Employee Updated Successfully'
      else
        render :edit
      end
    end

    def destroy
      @job.destroy
      redirect_to clients_jobs_path
    end



    private
    def job_params
      params.require(:job).permit(:title, :description, :start_date, :end_date, :client_id, skill_ids: [])
    end
    def find_job
      @job = Job.find(params[:id])
    end

  end
end

app/controllers/clients/proposals_controller.rb
module Clients
  class ProposalsController < ApplicationController
    before_action :authenticate_client!
    def index
      @proposals = current_client.proposals
    end
  end
end

app/controllers/freelancers/jobs_controller.rb
module Freelancers
  class JobsController < ApplicationController


    def index
      @jobs = Job.includes(:skills)
      @jobs = if params[:search].present?
               @jobs.search_bar(params[:search])
             else
               @jobs
             end
      @jobs = if params[:skills].present?
               @jobs.filter_skills(params[:skills])
             else
               @jobs
             end
    end
    #  @job = Job.includes(:skills).where(["title iLIKE ? OR description iLIKE ?", "%#{params[:search]}%",  "%#{params[:search]}%"]).joins(:skills).where(skills: {name: params[:skills]})
  end
end

  # .search_bar(params[:search]).filter_skills(params[:skills])

app/helpers/clients/jobs_helper.rb
module Clients::JobsHelper
end

app/helpers/freelancers/jobs_helper.rb
module Freelancers::JobsHelper
end

app/views/clients/jobs/_form.html.erb
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Title:</label>
      <div class="col-sm-8">
        <%= f.text_field :title, placeholder: 'Enter Job Title', class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Description:</label>
      <div class="col-sm-8">
        <%= f.text_area :description, placeholder: 'Enter description about Job', class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Skills:</label>
      <div class="col-sm-8">
        <%= f.select :skill_ids,  Skill.pluck(:name, :id), {}, multiple: true, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Started Date:</label>
      <div class="col-sm-8">
        <%= f.date_field :start_date, placeholder: 'Enter start date', class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Ended Date:</label>
      <div class="col-sm-8">
        <%= f.date_field :end_date, placeholder: 'Enter end date', class: "form-control" %>
      </div>
    </div>

app/views/clients/jobs/edit.html.erb
<div class="container">
  <h1>New Job</h1>
  <%= link_to("<< Back to List", clients_jobs_path, class: "btn btn-secondary btn-sm") %>
  <div><br><b></b></div>
  <%= form_with model: [:clients, @job] do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-group row">
      <div class=" offset-sm-2 col-sm-5">
        <%= f.submit 'Update', class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  <% end %>
</div>

app/views/clients/jobs/index.html.erb
<div class="container">
  <!-- search box-->
  <%= form_tag freelancers_jobs_path, method: 'get' do %>
    <div class="row">
      <div class="col-7">
        <%= text_field_tag :search, params[:search], class: 'form-control' %>
      </div>
      <div class="col-2">
        <%= select_tag :skills, options_for_select(Skill.all.map { |s| [s.name] }, params[:skills]), {:prompt => '-Skills-', class: "form-control"} %>
      </div>
      <div class="col-3">
        <%= submit_tag 'Search', class: "btn btn-info" %>
        <%= link_to 'Clear Search', freelancers_jobs_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <div class="row mt-3">
    <div class="col-12">
      <%= link_to 'Create New Job', new_clients_job_path, class: 'btn btn-primary btn-sm mb-2 mt-3' %>
      <% @jobs.each do |job| %>
        <div class="card mt-5 border-0">
          <div class="card-body">
            <h5 class="card-title"> <%= job.title %></h5>
            <hr>
            <p class="font-weight-bold">Description:</p>
            <div class="card-text"> <%= job.description %></div>
            <div class="card-text mt-4">
              <span class="font-weight-bold">Skills: </span><%= job.skills.map(&:name).map(&:capitalize).join(' | ') %>
            </div>
            <div class="card-text mt-4">
              <span class="font-weight-bold">Start Date:   </span> <%= job.start_date.strftime("%d %b %Y") %>
              <span class="font-weight-bold ml-4">   End Date:    </span>  <%= job.end_date.strftime("%d %b %Y") %>
            </div>
            <%= link_to 'Destroy', clients_job_path(job), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm mr-2 float-right" %>
            <%= link_to 'Edit', edit_clients_job_path(job), class: "btn btn-primary btn-sm mr-2 float-right" %>
            <%= link_to 'View', clients_job_path(job), class: "btn btn-info btn-sm mr-2 float-right" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/jobs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <%= form_with model: [:clients, @job] do |f| %>
        <div class="card border-0" style="">
          <div class="card-body">
            <h3>New Job</h3>
            <%= link_to("<< Back to List", clients_jobs_path, class: "btn btn-secondary btn-sm") %>
            <div><br><b></b></div>
            <h5 class="card-title">New Job</h5>

            <div class="card-text">
              <%= render(:partial => 'form', :locals => {:f => f}) %>

              <div class="form-group row">
                <div class=" offset-sm-2 col-sm-5">
                  <%= f.submit 'Create', class: "btn btn-primary btn-sm" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/jobs/show.html.erb
<div class="container">
  <div class="col-sm-6 offset-3">
    <div class="card mt-5 border-0">
      <div class="card-body">
        <h1>Job Detail</h1><br>
        <%= link_to("<< Back to List", clients_jobs_path, class: "btn btn-secondary btn-sm") %>
        <br><br>
        <p>
          <strong>Title:</strong>
          <%= @job.title.capitalize %>
        </p>
        <p>
          <strong>Description:</strong>
          <%= @job.description %>
        </p>
        <p>
          <strong>Department:</strong>
          <%= @job.skills.map(&:name).map(&:capitalize).join(',') %>
        </p>
        <p>
          <strong>Started Date:</strong>
          <%= @job.start_date %>
        </p>
        <p>
          <strong>End Date:</strong>
          <%= @job.end_date %>
        </p>
      </div>
    </div>
  </div>
</div>