config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  root :to => 'freelancers/jobs#index', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Freelancer' }, :as => "freelancer_root"
  root :to => 'clients/jobs#index', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Client' }, :as => "client_root"

  # root 'freelancers/jobs#index'

  devise_for :freelancers, :controllers => { :registrations => :registrations }
  devise_for :clients, :controllers => { :registrations => :registrations }

  namespace :clients do
    resources :contracts
    resources :proposals
    resources :jobs
  end

  namespace :freelancers do
    resources :contracts
    resources :proposals
    resources :jobs

  end

   resources :freelancers
end

app/models/freelancer.rb
class Freelancer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options dependent: :destroy do
    has_many :proposals
    has_many :jobs, through: :proposals

    has_many :contracts


    has_and_belongs_to_many :skills
    has_one_attached :image
    # has_one_attached :avatar
  end
  # validates :phone , phone:true
end

app/controllers/freelancers/contracts_controller.rb
module Freelancers
  class ContractsController < ApplicationController

    before_action :authenticate_freelancer!

    def index
      @contracts = current_freelancer.contracts
    end

    def update
      @contract = Contract.find(params[:id])
      @contract.update(end_date: DateTime.now)
      redirect_back(fallback_location: root_path)
    end

  end
end

app/controllers/freelancers/jobs_controller.rb
module Freelancers
  class JobsController < ApplicationController


    def index
      @jobs = Job.includes(:skills)
      @jobs = if params[:search].present?
               @jobs.search_bar(params[:search])
             else
               @jobs
             end
      @jobs = if params[:skills].present?
               @jobs.filter_skills(params[:skills])
             else
               @jobs
             end
    end
    #  @job = Job.includes(:skills).where(["title iLIKE ? OR description iLIKE ?", "%#{params[:search]}%",  "%#{params[:search]}%"]).joins(:skills).where(skills: {name: params[:skills]})
  end
end

  # .search_bar(params[:search]).filter_skills(params[:skills])

app/controllers/freelancers/proposals_controller.rb
module Freelancers

    class ProposalsController < ApplicationController
      before_action :authenticate_freelancer!

        def index
          @proposals = current_freelancer.proposals
        end
        def new
          @proposal = Proposal.new
          @proposal.job_id = params[:job_id]
        end

        def create
          @proposal = Proposal.new(proposal_params)          
          # @proposal.job_id = params[:job_id]
          @proposal.freelancer_id = current_freelancer.id        
          if @proposal.save

            redirect_to freelancers_jobs_path

          else
            render :new

          end
        end


        private
        def proposal_params
          params.require(:proposal).permit(:objective, :status, :job_id, documents: [])
        end
    end

end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController

  before_action :authenticate_freelancer!

  def show
    @freelancer = Freelancer.find(params[:id])
  end
end

app/helpers/freelancers/jobs_helper.rb
module Freelancers::JobsHelper
end

app/helpers/freelancers_helper.rb
module FreelancersHelper
end

app/views/freelancers/show.html.erb
<div class="container mt-5">
  <div class="card border-0">
    <div class="card-header"><h5 class="w-50 float-left">Profile</h5>
      <div class=" w-50 text-right float-right">
        <% if freelancer_signed_in? %>
          <%= link_to edit_freelancer_registration_path do %>
            Edit <i class="fas fa-pen"></i>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <% if current_user.image.attached? %>
            <%= image_tag current_user.image, class: "w-100 rounded-circle", alt: "profile image", data: {target: 'image-preview.image'} %>
          <% else %>
            <i class="fas fa-user-circle fa-5x"></i>
          <% end %>
        </div>
        <div class="card-text col-10">
          <div class="card-text font-weight-bold"> <%= current_user.first_name.capitalize %></div>
          <div class="card-text font-weight-bold mt-1"> <%= current_user.designation %></div>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p class="font-weight-bold mt-3 mb-0">Description:</p>
          <div class="card-text"> <%= current_user.overview %></div>
        </div>
      </div>
      <div class="row mt-4">
        <div class="col">
          <span class="font-weight-bold">Skills: </span><%= current_user.skills.map(&:name).map(&:capitalize).join('    |   ') %>
        </div>
      </div>
    </div>
  </div>
</div>