config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  root :to => 'freelancers/jobs#index', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Freelancer' }, :as => "freelancer_root"
  root :to => 'clients/jobs#index', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Client' }, :as => "client_root"

  # root 'freelancers/jobs#index'

  devise_for :freelancers, :controllers => { :registrations => :registrations }
  devise_for :clients, :controllers => { :registrations => :registrations }

  namespace :clients do
    resources :contracts
    resources :proposals
    resources :jobs
  end

  namespace :freelancers do
    resources :contracts
    resources :proposals
    resources :jobs

  end

   resources :freelancers
end

app/models/freelancer.rb
class Freelancer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options dependent: :destroy do
    has_many :proposals
    has_many :jobs, through: :proposals

    has_many :contracts


    has_and_belongs_to_many :skills
    has_one_attached :image
    # has_one_attached :avatar
  end
  # validates :phone , phone:true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :client

  scope :search_bar, -> (search) { where("title iLIKE ? OR description iLIKE ?", "%#{search}%", "%#{search}%") }
  # match pattern,                    wild_cards to match the search
  scope :filter_skills, -> (skills) { joins(:skills).where(skills: {name: skills}) }

  scope :recent, -> { order(created_at: :desc).limit(4) }

  with_options dependent: :destroy do
    has_many :proposals
    has_many :freelancers, through: :proposals
    has_and_belongs_to_many :skills
    # has_one :contract, through: :proposals
  end

  def applied? (current_freelancer)
    proposals.where(freelancer_id: current_freelancer.id).exists?
  end
end

app/controllers/clients/jobs_controller.rb
module Clients
  class JobsController < ApplicationController
    before_action :authenticate_client!
    before_action :find_job, only: [:show, :edit, :destroy, :update]

    def index
      @jobs = current_client.jobs
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new(job_params.merge(client_id: current_client.id))
      # @job = Job.new(job_params)
      # @job.client_id = current_client.id
      if @job.save
        redirect_to clients_jobs_path, notice: 'job Created Successfully'
      else
        render :new
      end
    end

    def update
      if @job.update(job_params)
        redirect_to clients_job_path(@job), notice: 'Employee Updated Successfully'
      else
        render :edit
      end
    end

    def destroy
      @job.destroy
      redirect_to clients_jobs_path
    end



    private
    def job_params
      params.require(:job).permit(:title, :description, :start_date, :end_date, :client_id, skill_ids: [])
    end
    def find_job
      @job = Job.find(params[:id])
    end

  end
end

app/controllers/freelancers/contracts_controller.rb
module Freelancers
  class ContractsController < ApplicationController

    before_action :authenticate_freelancer!

    def index
      @contracts = current_freelancer.contracts
    end

    def update
      @contract = Contract.find(params[:id])
      @contract.update(end_date: DateTime.now)
      redirect_back(fallback_location: root_path)
    end

  end
end

app/controllers/freelancers/jobs_controller.rb
module Freelancers
  class JobsController < ApplicationController


    def index
      @jobs = Job.includes(:skills)
      @jobs = if params[:search].present?
               @jobs.search_bar(params[:search])
             else
               @jobs
             end
      @jobs = if params[:skills].present?
               @jobs.filter_skills(params[:skills])
             else
               @jobs
             end
    end
    #  @job = Job.includes(:skills).where(["title iLIKE ? OR description iLIKE ?", "%#{params[:search]}%",  "%#{params[:search]}%"]).joins(:skills).where(skills: {name: params[:skills]})
  end
end

  # .search_bar(params[:search]).filter_skills(params[:skills])

app/controllers/freelancers/proposals_controller.rb
module Freelancers

    class ProposalsController < ApplicationController
      before_action :authenticate_freelancer!

        def index
          @proposals = current_freelancer.proposals
        end
        def new
          @proposal = Proposal.new
          @proposal.job_id = params[:job_id]
        end

        def create
          @proposal = Proposal.new(proposal_params)          
          # @proposal.job_id = params[:job_id]
          @proposal.freelancer_id = current_freelancer.id        
          if @proposal.save

            redirect_to freelancers_jobs_path

          else
            render :new

          end
        end


        private
        def proposal_params
          params.require(:proposal).permit(:objective, :status, :job_id, documents: [])
        end
    end

end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController

  before_action :authenticate_freelancer!

  def show
    @freelancer = Freelancer.find(params[:id])
  end
end

app/helpers/clients/jobs_helper.rb
module Clients::JobsHelper
end

app/helpers/freelancers/jobs_helper.rb
module Freelancers::JobsHelper
end

app/helpers/freelancers_helper.rb
module FreelancersHelper
end

app/views/freelancers/jobs/index.html.erb
<div class="container mt-5">
  <!-- search box-->
  <div class="row">
    <div class=" <%= freelancer_signed_in? ? 'col-9' : 'col-12' %>">
      <%= form_tag freelancers_jobs_path, method: 'get' do %>
        <div class="row">
          <div class="col-6">
            <%= text_field_tag :search, params[:search], class: 'form-control' %>
          </div>
          <div class="col-2">
            <%= select_tag :skills, options_for_select(Skill.all.map { |s| [s.name] }, params[:skills]), {:prompt => '-Skills-', class: "form-control"} %>
          </div>
          <div class="col-4">
            <%= submit_tag 'Search', class: "btn btn-info" %>
            <%= link_to 'Clear Search', freelancers_jobs_path, class: "btn btn-primary" %>
          </div>
      <% end %>
      <!-- card -->

      <div class="row mt-3">
        <div class="col">
          <% @jobs.each do |job| %>
            <div class="card mt-5">
              <div class="card-body mt-3">
                <h5 class="card-title"> <%= job.title %></h5>
                <hr>
                <p class="font-weight-bold">Description:</p>
                <div class="card-text"> <%= job.description %></div>
                <div class="card-text mt-4">
                  <span class="font-weight-bold">Skills: </span><%= job.skills.map(&:name).map(&:capitalize).join(' | ') %>
                </div>
                <% if freelancer_signed_in? && job.applied?(current_freelancer) %>
                  <%= button_tag 'Applied', disabled: true, class: 'btn btn-info btn-sm float-right' %>
                <% else %>
                  <%= link_to 'Apply', new_freelancers_proposal_path(job_id: job.id), remote: (freelancer_signed_in? ? true : false), class: 'btn btn-info btn-sm float-right px-3' %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      </div>
    </div>
    <!-- image-->
    <% if freelancer_signed_in? %>
      <div class="col-3">
        <div class="card border-0 w-75 float-right">
          <div class="row">
            <div class=" offset-3 col-6 text-center p-0">
              <% if current_user.image.attached? %>
                <%= image_tag current_user.image, class: "w-100 mt-4 rounded-circle", alt: "profile image", data: {target: 'image-preview.image'} %>
              <% else %>
                <i class="fas fa-user-circle fa-5x"></i>
              <% end %>
            </div>
          </div>
          <div class="card-body">
            <div class="card-text mt-2 text-center"><%= current_freelancer.first_name.capitalize %></div>
            <div class="card-text mx-2 text-center"><%= current_freelancer.designation&.capitalize %></div>
            <hr>
            <div class="text-center mt-3">
              <i class="fa-check-circle <%= current_freelancer.proposals.none? ? 'far' : 'fas ' %>"></i> <%= current_freelancer.proposals.count %>
              <i>Proposals </i></div>
            <div class="text-center">
              <i class="fa-check-circle <%= current_freelancer.contracts.none? ? 'far' : 'fas ' %>"></i> <%= current_freelancer.contracts.count %>
              <i> Contracts </i></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>