config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  root :to => 'freelancers/jobs#index', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Freelancer' }, :as => "freelancer_root"
  root :to => 'clients/jobs#index', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Client' }, :as => "client_root"

  # root 'freelancers/jobs#index'

  devise_for :freelancers, :controllers => { :registrations => :registrations }
  devise_for :clients, :controllers => { :registrations => :registrations }

  namespace :clients do
    resources :contracts
    resources :proposals
    resources :jobs
  end

  namespace :freelancers do
    resources :contracts
    resources :proposals
    resources :jobs

  end

   resources :freelancers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jobs, dependent: :destroy
  has_many :proposals, through: :jobs
  has_many :contracts, through: :proposals

end

app/models/contract.rb
class Contract < ApplicationRecord

  after_create :send_message

  belongs_to :freelancer
  belongs_to :proposal
  has_one :job, :through => :proposal

  def send_message
    TwilioClient.new.send_text(freelancer, "#{job.client.email} has hired you for job: #{job.title}")
  end
end

app/models/freelancer.rb
class Freelancer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options dependent: :destroy do
    has_many :proposals
    has_many :jobs, through: :proposals

    has_many :contracts


    has_and_belongs_to_many :skills
    has_one_attached :image
    # has_one_attached :avatar
  end
  # validates :phone , phone:true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :client

  scope :search_bar, -> (search) { where("title iLIKE ? OR description iLIKE ?", "%#{search}%", "%#{search}%") }
  # match pattern,                    wild_cards to match the search
  scope :filter_skills, -> (skills) { joins(:skills).where(skills: {name: skills}) }

  scope :recent, -> { order(created_at: :desc).limit(4) }

  with_options dependent: :destroy do
    has_many :proposals
    has_many :freelancers, through: :proposals
    has_and_belongs_to_many :skills
    # has_one :contract, through: :proposals
  end

  def applied? (current_freelancer)
    proposals.where(freelancer_id: current_freelancer.id).exists?
  end
end

app/models/proposal.rb
class Proposal < ApplicationRecord

  after_create :send_message

  belongs_to :freelancer
  belongs_to :job
  has_one :contract, dependent: :destroy
  has_many_attached :documents

  def send_message
    TwilioClient.new.send_text(job.client, "#{freelancer.email} has applied for #{job.title}")
  end
end

app/models/skill.rb
class Skill < ApplicationRecord

  with_options dependent: :destroy do
    has_and_belongs_to_many :freelancers
    has_and_belongs_to_many :jobs
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :user_signed_in?
  helper_method :current_user

    def authenticate_user!
      authenticate_client! || authenticate_freelancer!
    end

    def user_signed_in?
      client_signed_in? || freelancer_signed_in?
    end

    def current_user
      current_client || current_freelancer
    end

  protected

    def configure_permitted_parameters
      added_attrs = [:first_name, :last_name, :designation, :overview, :email, :password, :password_confirmation, :remember_me, :image, :phone, skill_ids: []]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end

  def after_sign_in_path_for(resource)
    if resource.is_a? Client
      clients_jobs_path
    elsif resource.is_a? Freelancer
      freelancers_jobs_path
    else
      super
    end
  end
end

app/controllers/clients/jobs_controller.rb
module Clients
  class JobsController < ApplicationController
    before_action :authenticate_client!
    before_action :find_job, only: [:show, :edit, :destroy, :update]

    def index
      @jobs = current_client.jobs
    end

    def new
      @job = Job.new
    end

    def create
      @job = Job.new(job_params.merge(client_id: current_client.id))
      # @job = Job.new(job_params)
      # @job.client_id = current_client.id
      if @job.save
        redirect_to clients_jobs_path, notice: 'job Created Successfully'
      else
        render :new
      end
    end

    def update
      if @job.update(job_params)
        redirect_to clients_job_path(@job), notice: 'Employee Updated Successfully'
      else
        render :edit
      end
    end

    def destroy
      @job.destroy
      redirect_to clients_jobs_path
    end



    private
    def job_params
      params.require(:job).permit(:title, :description, :start_date, :end_date, :client_id, skill_ids: [])
    end
    def find_job
      @job = Job.find(params[:id])
    end

  end
end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController

  before_action :authenticate_freelancer!

  def show
    @freelancer = Freelancer.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'home'

  def index
    @jobs = Job.recent
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(resource)
    if freelancer_signed_in?
      freelancer_path(resource)
    else
      edit_client_registration_path(resource)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients/jobs_helper.rb
module Clients::JobsHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/freelancers/jobs_helper.rb
module Freelancers::JobsHelper
end

app/helpers/freelancers_helper.rb
module FreelancersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RemoteWork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f177f939a1.js"></script>
  </head>

  <body class="body-color">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg  navbar-dark bg-primary ">
      <div class="container">
        <% if user_signed_in? %>
          <%= link_to freelancer_signed_in? ? freelancers_jobs_path : clients_jobs_path, alt: "Brand", class: 'navbar-brand' do %>
            <%= image_tag "Logo.png" %>
          <% end %>
        <% else %>
          <%= link_to root_path alt: "Brand", class: 'navbar-brand' do %>
            <%= image_tag "Logo.png" %>
          <% end %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Jobs', freelancer_signed_in? ? freelancers_jobs_path : clients_jobs_path, class: "nav-link" %>
              </li>
              <li class="nav-item">

                <%= link_to 'Proposals', freelancer_signed_in? ? freelancers_proposals_path : clients_proposals_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Contracts', freelancer_signed_in? ? freelancers_contracts_path : clients_contracts_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <div class="dropdown">
                <button class=" btn btn-link mr-2 text-white" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <% if current_user.respond_to?(:image) && current_user.image.attached? %>
                    <%= image_tag current_user.image, width: 30, class: 'rounded-circle', alt: "profile image", data: {target: 'image-preview.image'} %>
                  <% else %>
                    <i class="fas fa-user-circle fa-1x"></i>
                  <% end %>

                  <%= "#{current_user.first_name.capitalize  }  #{current_user.last_name.capitalize }" %>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                  <% if freelancer_signed_in? %>
                    <%= link_to '  Profile', edit_freelancer_registration_path, class: "dropdown-item fas fa-user" %>
                    <%= link_to '  Logout', destroy_freelancer_session_path, method: :delete, class: "dropdown-item fas fa-power-off" %>
                  <% else %>
                    <%= link_to ' Account', edit_client_registration_path, class: "dropdown-item fas fa-user" %>
                    <%= link_to ' Logout', destroy_client_session_path, method: :delete, class: "dropdown-item fas fa-power-off" %>
                  <% end %>
                </div>
              </div>
            <% else %>
              <div class="dropdown">
                <button class="btn btn-secondary btn-sm rounded-pill px-3" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Sign_up
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                  <%= link_to 'Client', new_client_registration_path, class: "dropdown-item" %>
                  <%= link_to 'Freelancer', new_freelancer_registration_path, class: "dropdown-item" %>
                </div>
              </div>

              <div class="dropdown">
                <button class="btn btn-secondary btn-sm  ml-3 rounded-pill px-4" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Login
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                  <%= link_to 'Client', new_client_session_path, class: "dropdown-item btn" %>
                  <%= link_to 'Freelancer', new_freelancer_session_path, class: "dropdown-item btn" %>
                </div>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-5">
      <% if notice %>
        <div class="alert alert-info alert-dismissible mt-5" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-info alert-dismissible mt-5">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= alert %></div>
      <% end %>
    </div>

    <div class="mt-5"><%= yield %></div>
    <div id="modal"></div>
  <!--      <footer class="bg-dark footer"> <p class="text-white fixed-bottom">copyright@2019</p></footer>-->
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RemoteWork</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f177f939a1.js"></script>
  </head>

  <body class="body-color">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg  shadow fixed-top nav--home">
      <div class="container">
        <%= link_to  root_path alt: "Brand", class: 'navbar-brand' do  %>
          <%= image_tag "Logo.png" %>
        <% end %>

          <!--search bar-->
          <%= form_tag freelancers_jobs_path, method: 'get' do %>
                <%= text_field_tag :search, params[:search], class: 'form-control ml-5 rounded-pill mt-2 search', placeholder: 'Search Jobs' %>
          <% end %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Jobs',  freelancer_signed_in? ? freelancers_jobs_path: clients_jobs_path,  class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Proposals',  freelancer_signed_in? ? freelancers_proposals_path : clients_proposals_path,  class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Contracts',  freelancer_signed_in? ? freelancers_contracts_path : clients_contracts_path,  class: "nav-link" %>
              </li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <div class="dropdown">
                <button class=" btn btn-link mr-2"  id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <% if current_user.respond_to?(:image) && current_user.image.attached? %>
                    <%= image_tag current_user.image, width: 30, class: 'rounded-circle' ,alt: "profile image", data: {target: 'image-preview.image'} %>
                  <% else %>
                    <i class="fas fa-user-circle fa-1x" ></i>
                  <% end %>

                  <%= "#{current_user.first_name.capitalize  }  #{current_user.last_name.capitalize }" %>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                  <% if freelancer_signed_in? %>
                    <%= link_to 'Profile', edit_freelancer_registration_path, class: "dropdown-item" %>
                    <%= link_to 'Logout', destroy_freelancer_session_path, method: :delete,  class: "dropdown-item" %>
                  <% else %>
                    <%= link_to 'Logout', destroy_client_session_path, method: :delete,  class: "dropdown-item" %>
                  <% end %>
                </div>
              </div>
            <% else %>
              <div class="dropdown">
                <button class="btn btn-sm text-white rounded-pill" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Sign_up
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                  <%= link_to  'Client', new_client_registration_path, class: "dropdown-item" %>
                  <%= link_to  'Freelancer', new_freelancer_registration_path, class: "dropdown-item"  %>
                </div>
              </div>

              <div class="dropdown">
                <button class="btn btn-sm  ml-3 text-white rounded-pill btn-success px-3" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Login
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
                  <%= link_to  'Client', new_client_session_path, class: "dropdown-item btn" %>
                  <%= link_to  'Freelancer', new_freelancer_session_path, class: "dropdown-item btn" %>
                </div>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
    <div id="modal"></div>

    <footer class="container-fluid bg-4 text-center bg-primary">
      <p class="text-white">Copyright2019 www.RemoteWork.com</p>
    </footer>
  </body>
</html>